; Script generated by Antigravity for Kho Hang An Nam
#define MyAppName "Kho Hàng An Nam"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Laptop An Nam"
#define MyAppURL "https://annamlaptop.vn"
#define MyAppExeName "KhoHangAnNam.exe"

[Setup]
AppId={{8B2D5D6E-3C4A-4F8B-9E1D-7C5F3A1B9D2E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Kho Hang An Nam
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=installer
OutputBaseFilename=setupKhoHang
SetupIconFile=static\app_icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\app_icon.ico
UninstallDisplayName={#MyAppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
english.CreateDesktopIcon=Tạo biểu tượng ngoài màn hình chính (Desktop)
english.LaunchProgram=Khởi động Kho Hàng An Nam ngay

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "Tùy chọn bổ sung:"; Flags: checkedonce

[Files]
Source: "dist\KhoHangAnNam\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram}"; Flags: nowait postinstall skipifsilent
